# Generated by Django 5.0.4 on 2024-04-17 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_membresias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Familiar', 'Familiar'), ('Empresearial', 'Empresarial')], max_length=20)),
                ('tipo_servicios', models.CharField(choices=[('Basicos', 'Basicos'), ('Completa', 'Completa'), ('Coaching', 'Coaching'), ('Nutriólogo', 'Nutriólogo')], max_length=20)),
                ('tipo_plan', models.CharField(choices=[('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Trimestral', 'Trimestral'), ('Bimestral', 'Bimestral'), ('Mensual', 'Mensual'), ('Semanal', 'Semanal'), ('Diaria', 'Diaria')], max_length=20)),
                ('nivel', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('Diamante', 'Diamante')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cortecia', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateTimeField(auto_now=True)),
                ('fotografia', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F'), ('No Binario', 'N/B')], default='Masculino', max_length=20)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=10)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='tbl_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_nombre', models.CharField(max_length=50)),
                ('d_apellidoPaterno', models.CharField(max_length=50)),
                ('d_apellidoMaterno', models.CharField(max_length=50)),
                ('d_direccion', models.CharField(max_length=150)),
                ('d_telefono', models.CharField(max_length=15)),
                ('d_correo', models.CharField(max_length=100)),
                ('d_contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tb_usuarios',
            fields=[
                ('Persona_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapi.tb_personas')),
                ('Nombre_Usuario', models.IntegerField(unique=True)),
                ('Password', models.BinaryField(null=True)),
                ('Tipo', models.CharField(choices=[('Empleado', 'Empleado'), ('Visitante', 'Visitante'), ('Miembro', 'Miembro'), ('Instructor', 'Instructor')], max_length=20, null=True)),
                ('Estatus_Conexion', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Banned', 'Banned')], max_length=10, null=True)),
                ('Ultima_Conexion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_miembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membresias_activa', models.BooleanField()),
                ('antiguedad', models.CharField(max_length=50)),
                ('personas_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.tb_personas')),
            ],
        ),
        migrations.CreateModel(
            name='tb_membresias_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Ultima_Visita', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.BooleanField()),
                ('membresias_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.tb_membresias')),
                ('usuarios_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.tb_usuarios')),
            ],
        ),
    ]
